name: Run Cypress Tests in Docker

on:
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened

jobs:
  cypress-tests:
    name: 'Cypress default config tests'
    runs-on: ubuntu-20.04
    container:
      image: cypress/browsers:latest
      options: --user 1001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress default command tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
